### ISSUE TITLE
Allow developer to specify package-identifier or keep it.

### ISSUE THREAD

**Issue by allstarschh** [johnathan79717/fxos-package-signing-tool#2]
Currently when the signed package is generated, a new package-identifier is generated each time, even for the same package.
This might not be what developers want since new package-identifier means a totally different package than the original one, and we might break the update since newer version won't share the same package-identifier with older one and will be considered as a different package.

**Comment by johnathan79717** [comment]
If there's already a package-identifier in the manifest, this tool won't generate a new one.
This tool will use the existing one in the manifest, unless it's missing.

Checkout https://github.com/johnathan79717/fxos-package-signing-tool/blob/master/make_web_package.py#L105

**Comment by allstarschh** [comment]
great, thanks for explaining.
